### ISSUE TITLE
JEI Area Fixer crashes Minecraft before startup

### ISSUE THREAD

**Issue by prismfruit** [ZZZank/JEIAreaFixer#8]
Hello, I commented on [Forge](https://www.curseforge.com/minecraft/mc-mods/jei-area-fixer/comments) about this issue already, here's the info from latest.log as requested.

https://pastebin.com/guFBcQPk

Basically, JEI Area Fixer crashes my game before it even has a chance to open a window and I'm not sure what's causing it to do that. I struggle to read logs and crash reports, so apologies if it's something obvious like a mod conflict.

**Comment by ZZZank** [comment]
Never seen any log like this before, but I got two theories based on these lines:
```
Caused by: java.lang.NoClassDefFoundError: zone/rong/mixinbooter/IEarlyMixinLoader
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_51]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_51]
...
```

- Check if [MixinBooter](https://www.curseforge.com/minecraft/mc-mods/mixin-booter) is installed
- If MixinBooter is already installed, you might need to replace the Java that your launcher is using. I assume that you're using CurseForge App because `1.8.0_51` is really ancient Java version, and CF App is the only launcher I know that is using this Java version. You will need to goto "settings" -> "Minecraft" -> scroll down to "java versions" section -> choose another Java for "java 8"

**Comment by prismfruit** [comment]
Forcing Minecraft Launcher to use the newest Java version seems to have worked, thanks!

I use a RLCraft modpack I rescued from Twitch launcher's demise, which explains why it was using such an old Java version.

**Comment by ZZZank** [comment]
closing this issue since it's solved. I'll add a Q&A section to CurseForge page soon
